#!/usr/bin/env python3
"""make_geo.py: the coastlines ORBIT draws, from Natural Earth (public domain) via the world-atlas npm package (ISC).

    python3 video/src/worlds/orbit/tools/make_geo.py [--wa=DIR]     (DIR = an unpacked world-atlas@2 package)

Without --wa it runs `npm pack world-atlas@2.0.2` into a temp dir (the npm registry is reachable from the sandbox).
Writes video/src/worlds/orbit/geo.gen.js:
  WORLD    land rings at 1:110m, [lon, lat] x 1000 as flat int arrays (closed rings, first point not repeated)
  BRITAIN  1:10m coast pieces clipped to the British Isles / Channel / Low Countries box (Halley's 1715 map, S65)
  ANATOLIA 1:10m coast pieces clipped to Anatolia and its seas (the dive, S74; the pull-back, S77)
Clipped pieces are open polylines (coast only), closed when the whole ring lies inside the box. Simplified with
Douglas-Peucker (tolerance in degrees, longitude scaled by cos(lat)); islands below a minimum extent are dropped.
"""
import json, math, os, subprocess, sys, tempfile, pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / 'geo.gen.js'


def topo_rings(path):
    d = json.load(open(path))
    sx, sy = d['transform']['scale']; tx, ty = d['transform']['translate']
    arcs = []
    for a in d['arcs']:
        x = y = 0; pts = []
        for dx, dy in a:
            x += dx; y += dy; pts.append((x * sx + tx, y * sy + ty))
        arcs.append(pts)
    def arc(i):
        return arcs[i] if i >= 0 else arcs[~i][::-1]
    rings = []
    def ring(idx):
        pts = []
        for i in idx:
            a = arc(i)
            pts.extend(a if not pts else a[1:])
        if len(pts) > 1 and pts[0] == pts[-1]: pts = pts[:-1]
        return pts
    for g in d['objects']['land']['geometries']:
        polys = g['arcs'] if g['type'] == 'MultiPolygon' else [g['arcs']]
        for poly in polys:
            for k, r in enumerate(poly):
                rings.append((ring(r), k > 0))
    return rings


def dp(pts, tol, closed=False):
    if len(pts) < 3: return pts
    def d2(p, a, b):
        c = math.cos(math.radians((a[1] + b[1]) / 2))
        ax, ay, bx, by, px, py = a[0] * c, a[1], b[0] * c, b[1], p[0] * c, p[1]
        vx, vy = bx - ax, by - ay; L = vx * vx + vy * vy
        if L == 0: return (px - ax) ** 2 + (py - ay) ** 2
        t = max(0, min(1, ((px - ax) * vx + (py - ay) * vy) / L))
        return (px - ax - t * vx) ** 2 + (py - ay - t * vy) ** 2
    if closed:   # split at the farthest pair so both halves simplify independently
        far = max(range(len(pts)), key=lambda i: (pts[i][0] - pts[0][0]) ** 2 + (pts[i][1] - pts[0][1]) ** 2)
        a = dp(pts[:far + 1], tol); b = dp(pts[far:] + [pts[0]], tol)
        return a[:-1] + b[:-1]
    keep = [False] * len(pts); keep[0] = keep[-1] = True
    st = [(0, len(pts) - 1)]; t2 = tol * tol
    while st:
        i, j = st.pop()
        best, bi = -1, -1
        for k in range(i + 1, j):
            v = d2(pts[k], pts[i], pts[j])
            if v > best: best, bi = v, k
        if best > t2: keep[bi] = True; st += [(i, bi), (bi, j)]
    return [p for p, k in zip(pts, keep) if k]


def clip_pieces(ring, box, margin=0.0):
    x0, y0, x1, y1 = box[0] - margin, box[1] - margin, box[2] + margin, box[3] + margin
    inside = [x0 <= p[0] <= x1 and y0 <= p[1] <= y1 for p in ring]
    if all(inside): return [(ring, True)]
    if not any(inside): return []
    n = len(ring); start = inside.index(False)
    pieces, cur = [], []
    for k in range(n + 1):
        i = (start + k) % n
        if inside[i]: cur.append(ring[i])
        elif cur:
            pieces.append((cur, False)); cur = []
    if cur: pieces.append((cur, False))
    return [p for p in pieces if len(p[0]) > 1]


def signed_area(pts):
    a = 0
    for i in range(len(pts)):
        x0, y0 = pts[i]; x1, y1 = pts[(i + 1) % len(pts)]
        a += x0 * y1 - x1 * y0
    return a / 2


def extent(pts):
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    c = math.cos(math.radians(sum(ys) / len(ys)))
    return max((max(xs) - min(xs)) * c, max(ys) - min(ys))


def enc(pts):
    return '[' + ','.join(f'{round(p[0] * 1000)},{round(p[1] * 1000)}' for p in pts) + ']'


def main():
    wa = next((a.split('=', 1)[1] for a in sys.argv[1:] if a.startswith('--wa=')), None)
    if not wa:
        tmp = tempfile.mkdtemp()
        subprocess.run(['npm', 'pack', 'world-atlas@2.0.2', '--silent'], cwd=tmp, check=True)
        subprocess.run(['tar', '-xzf', 'world-atlas-2.0.2.tgz'], cwd=tmp, check=True)
        wa = os.path.join(tmp, 'package')
    out = ['// geo.gen.js: GENERATED by tools/make_geo.py from Natural Earth (public domain) via world-atlas@2.0.2 (ISC).',
           '// Coordinates are [lon, lat] x 1000 as flat int arrays. Do not edit by hand.', '']
    # the world at 1:110m: every ring (holes flagged), lightly simplified
    world = []
    for r, hole in topo_rings(os.path.join(wa, 'land-110m.json')):
        s = dp(r, .06, closed=True)
        if len(s) >= 3 and extent(s) > .4: world.append((s, hole))
    out.append('export const WORLD = [' + ','.join(f'{{h:{1 if h else 0},p:{enc(s)}}}' for s, h in world) + '];')
    rings10 = topo_rings(os.path.join(wa, 'land-10m.json'))
    regions = {
        'BRITAIN': dict(box=(-11.0, 48.0, 9.0, 59.5), tol=.006, minExt=.12),
        'ANATOLIA': dict(box=(19.0, 30.5, 50.0, 47.5), tol=.01, minExt=.18),
    }
    for name, R in regions.items():
        pieces = []
        for r, hole in rings10:
            # sea side: +1 = the sea lies to the LEFT of the direction of travel (lon right, lat up)
            ccw = signed_area(r) > 0
            sea = (-1 if ccw else 1) * (-1 if hole else 1)
            for p, closed in clip_pieces(r, R['box']):
                if extent(p) < R['minExt']: continue
                s = dp(p, R['tol'], closed=closed)
                if len(s) >= 2: pieces.append((s, closed, sea))
        out.append(f'export const {name} = [' + ','.join(f'{{c:{1 if c else 0},s:{sea},p:{enc(s)}}}' for s, c, sea in pieces) + '];')
        print(name, len(pieces), 'pieces', sum(len(x[0]) for x in pieces), 'points')
    print('WORLD', len(world), 'rings', sum(len(s) for s, _ in world), 'points')
    # land masks (PNG, 255 = land): the dive's region from 1:10m, the world from 1:50m (equirectangular)
    from PIL import Image, ImageDraw
    def mask(rings, box, w, name):
        x0, y0, x1, y1 = box; h = round(w * (y1 - y0) / (x1 - x0))
        im = Image.new('L', (w, h), 0); dr = ImageDraw.Draw(im)
        X = lambda p: ((p[0] - x0) / (x1 - x0) * w, (y1 - p[1]) / (y1 - y0) * h)
        for r, hole in sorted(rings, key=lambda q: q[1]):          # outer rings first, then holes cut out
            if len(r) < 3: continue
            # unwrap rings that cross the antimeridian (Chukotka, Fiji): continuous longitude, drawn at -360/0/+360
            u = [r[0]]
            for p in r[1:]:
                lon = p[0]
                while lon - u[-1][0] > 180: lon -= 360
                while lon - u[-1][0] < -180: lon += 360
                u.append((lon, p[1]))
            for sh in (-360, 0, 360):
                q = [(a + sh, b) for a, b in u]
                xs = [p[0] for p in q]; ys = [p[1] for p in q]
                if max(xs) < x0 - 1 or min(xs) > x1 + 1 or max(ys) < y0 - 1 or min(ys) > y1 + 1: continue
                dr.polygon([X(p) for p in q], fill=0 if hole else 255)
        im.save(HERE.parent / name, optimize=True)
        print('wrote', name, im.size, (HERE.parent / name).stat().st_size, 'bytes')
    mask(rings10, (19.0, 30.5, 50.0, 47.5), 2048, 'land_anatolia.png')
    mask(topo_rings(os.path.join(wa, 'land-50m.json')), (-180, -90, 180, 90), 4096, 'land_world.png')
    OUT.write_text('\n'.join(out) + '\n')
    print('wrote', OUT, OUT.stat().st_size, 'bytes')


if __name__ == '__main__':
    main()
